keys:
  - &c4patino_arisu age1mt673rdh9g4ylt4se20vnv2mf7qul0ax9mwlhy5x97h4pxyypaascdyccn
  - &c4patino_kokoro age1u0jz3r6tz3a7rz64j02xpwuykslq9zruxasutvmum07ya7k3xduseme93n 
creation_rules:
  - path_regex: secrets/sops/secrets.yaml
    key_groups:
      - age:
        - *c4patino_arisu
        - *c4patino_kokoro

