name: ci

on:
  push:
    branches: ["main"]
    tags: ["v*.*.*"]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: ["*"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  format:
    uses: c4patino/actions/.github/workflows/format.yml@main
    with:
      language: nix
